import './../blocks/header/header.js'
import './../blocks/logo/logo.js'
import './../blocks/menu/menu.js'
import './../blocks/table-gold/table-gold.js'
import './../blocks/slider/slider.js'
import './../blocks/blocks-row/blocks-row.js'
import './../blocks/card-link/card-link.js'
import './../blocks/footer/footer.js'